### ISSUE TITLE
Request for Deployment Instructions or Workflow（请求部署说明或者Github工作流）

### ISSUE THREAD

**Issue by Vinci-217** [Plumbiu/blog#19]
Hi !

I've been exploring this project and find it really interesting! However, I’ve run into some difficulties when trying to deploy it, and I keep encountering errors during the process. I'm not entirely sure what steps to follow for a successful deployment.

Would it be possible to add detailed deployment instructions or perhaps a workflow for deployment within the repository? This would be incredibly helpful for users like myself who are eager to get the project running.

Thanks so much for your time and consideration!

我一直在探索这个项目，感觉非常有趣！不过，在尝试部署时，我遇到了一些困难，并且在部署过程中不断遇到错误。我不太确定正确的部署步骤。

请问是否可以在仓库中添加详细的部署说明，或者提供一个部署的工作流？这将对像我这样的用户非常有帮助，帮助我们顺利运行这个项目。

非常感谢你的时间和考虑！

**Comment by Plumbiu** [comment]
看了一下你的仓库，修改一下这个变量，https://github.com/Vinci-217/Vinci-217.github.io/blob/vinci/src/constants.ts#L18，因为我这里用了四个文件夹区分不同笔记，看你只用了一个

**Comment by Vinci-217** [comment]
> 看了一下你的仓库，修改一下这个变量，[https://github.com/Vinci-217/Vinci-217.github.io/blob/vinci/src/constants.ts#L18，因为我这里用了四个文件夹区分不同笔记，看你只用了一个](https://github.com/Vinci-217/Vinci-217.github.io/blob/vinci/src/constants.ts#L18%EF%BC%8C%E5%9B%A0%E4%B8%BA%E6%88%91%E8%BF%99%E9%87%8C%E7%94%A8%E4%BA%86%E5%9B%9B%E4%B8%AA%E6%96%87%E4%BB%B6%E5%A4%B9%E5%8C%BA%E5%88%86%E4%B8%8D%E5%90%8C%E7%AC%94%E8%AE%B0%EF%BC%8C%E7%9C%8B%E4%BD%A0%E5%8F%AA%E7%94%A8%E4%BA%86%E4%B8%80%E4%B8%AA)

![image](https://github.com/user-attachments/assets/d0c6fe94-76d5-468a-9eeb-4b7eb304588a)

感谢您的回复，不过我尝试按照您的方法进行了修改，或者是切换到了您的源文件的分支，貌似都不能解决问题。图示是我的页面截图，显示出了README的内容。我猜测应该是部署的过程中出现了问题。请问能否给出在Github Page上部署的方式呢？

非常感谢您的时间！

**Comment by Plumbiu** [comment]
待会我尝试一下部署 github page，晚些写一个流程

**Comment by Plumbiu** [comment]
添加了 [说明](https://github.com/Plumbiu/blog/blob/main/deploy.md) 和 [工作流](https://github.com/Plumbiu/blog/blob/main/.github/workflows/nextjs.yml)，应该没问题 https://plumbiu.github.io/blog/

**Comment by Vinci-217** [comment]
> 添加了 [说明](https://github.com/Plumbiu/blog/blob/main/deploy.md) 和 [工作流](https://github.com/Plumbiu/blog/blob/main/.github/workflows/nextjs.yml)，应该没问题 https://plumbiu.github.io/blog/

部署成功了，非常感谢。另外请问能否打开仓库的Template权限呢，这样使用会更方便一点。

**Comment by Plumbiu** [comment]
> > 添加了 [说明](https://github.com/Plumbiu/blog/blob/main/deploy.md) 和 [工作流](https://github.com/Plumbiu/blog/blob/main/.github/workflows/nextjs.yml)，应该没问题 https://plumbiu.github.io/blog/
> 
> 部署成功了，非常感谢。另外请问能否打开仓库的Template权限呢，这样使用会更方便一点。

暂时不考虑，因为里面有很多“自定义”的内容，做成模板的工作量太大，以后维护起来也很复杂

**Comment by Vinci-217** [comment]
> > > 添加了 [说明](https://github.com/Plumbiu/blog/blob/main/deploy.md) 和 [工作流](https://github.com/Plumbiu/blog/blob/main/.github/workflows/nextjs.yml)，应该没问题 https://plumbiu.github.io/blog/
> > 
> > 
> > 部署成功了，非常感谢。另外请问能否打开仓库的Template权限呢，这样使用会更方便一点。
> 
> 暂时不考虑，因为里面有很多“自定义”的内容，做成模板的工作量太大，以后维护起来也很复杂

好的，感谢回复！
